import type { AppSnapshot } from "../types";

export function snapshotFixture(now = Date.now()): AppSnapshot {
  return {
    settings: {
      schemaVersion: 13,
      listeningSource: {
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        executableName: "MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        lastPid: 4242,
      },
      captureMode: "process_tree",
      outputDeviceId: "Speakers (PRO)",
      rescueScanEnabled: false,
      autoAttach: true,
      hotkeys: {
        toggleListening: "F8",
        pushToTalk: "F9",
        copyLatest: "F10",
        editOverlay: "F7",
      },
      overlay: {
        opacity: 0.94,
        fontScale: 1,
        fadeSeconds: 8,
        maxItems: 4,
        width: 420,
        height: 236,
      },
      vad: {
        processTree: { vadThreshold: 0.5, gainDb: 0 },
        systemOutput: { vadThreshold: 0.35, gainDb: 9 },
        silenceMs: 500,
        preRollMs: 200,
        maxUtteranceMs: 12000,
      },
      groq: {
        configured: true,
        incomingSttModel: "whisper-large-v3",
        microphoneSttModel: "whisper-large-v3-turbo",
        translationModel: "openai/gpt-oss-20b",
        monthlyBudgetMicrousd: 2_000_000,
        usageMonth: "2026-08",
        actualAudioMillis: 60_000,
        billedAudioMillis: 70_000,
        promptTokens: 120,
        completionTokens: 40,
        estimatedSpendMicrousd: 5_000,
      },
      glossary: [{ source: "Mistfall", target: "Mistfall" }],
    },
    runtime: {
      listening: true,
      microphoneActive: false,
      overlayEditMode: false,
      workerReady: true,
      workerModel: "silero-vad",
      groqSttBusy: false,
      groqStatus: "Groq พร้อมใช้งาน",
      budgetExhausted: false,
      attachedSource: {
        pid: 4242,
        name: "MistfallHunter-Win64-Shipping.exe",
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        isMistfall: true,
      },
      effectiveCapturePid: 4000,
      effectiveCaptureName: "MistfallHunter.exe",
      effectiveOutputDeviceId: undefined,
      effectiveOutputDeviceName: undefined,
      effectiveOutputDeviceIsDefault: false,
      audioRmsDbfs: -28,
      audioPeakDbfs: -10,
      audioLastSeenAtMs: now,
      vadActive: false,
      effectiveVadThreshold: 0.5,
      effectiveVadGainDb: 0,
      effectiveVadAutoGainDb: 0,
      droppedAudioChunks: 0,
      statusMessage: "กำลังฟัง Mistfall Hunter",
    },
    history: [
      {
        segmentId: "incoming-1",
        stream: "incoming",
        sourceDisplayName: "Mistfall Hunter",
        originalLanguage: "en",
        originalText: "Join us at the north gate.",
        translatedText: "ไปรวมกันที่ประตูเหนือ",
        status: "success",
        createdAtMs: now - 500,
      },
      {
        segmentId: "mic-1",
        stream: "microphone",
        originalLanguage: "th",
        originalText: "กำลังไป",
        translatedText: "On my way.",
        status: "success",
        createdAtMs: now - 1_000,
      },
    ],
  };
}
