import type { AppSnapshot } from "../types";

export function snapshotFixture(now = Date.now()): AppSnapshot {
  return {
    settings: {
      schemaVersion: 11,
      selectedProcess: {
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        executableName: "MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        lastPid: 4242,
      },
      gameCaptureMode: "process_tree",
      gameOutputDeviceId: "Speakers (PRO)",
      systemOutputCloudScan: false,
      voiceChat: {
        enabled: true,
        autoDetect: true,
        selectedProcess: {
          executablePath: "C:\\Users\\User\\AppData\\Local\\Discord\\Discord.exe",
          executableName: "Discord.exe",
          displayName: "Discord",
          lastPid: 7210,
        },
        rescueScan: true,
        vad: { vadThreshold: 0.35, gainDb: 6 },
      },
      autoAttach: true,
      hotkeys: {
        toggleListening: "F8",
        pushToTalk: "F9",
        copyLatest: "F10",
        editOverlay: "F7",
      },
      overlay: {
        opacity: 0.94,
        fontScale: 1,
        fadeSeconds: 8,
        maxItems: 4,
        width: 420,
        height: 236,
      },
      vad: {
        processTree: { vadThreshold: 0.5, gainDb: 0 },
        systemOutput: { vadThreshold: 0.35, gainDb: 9 },
        silenceMs: 500,
        preRollMs: 200,
        maxUtteranceMs: 12000,
      },
      groq: {
        configured: true,
        gameSttModel: "whisper-large-v3",
        microphoneSttModel: "whisper-large-v3-turbo",
        translationModel: "openai/gpt-oss-20b",
        monthlyBudgetMicrousd: 2_000_000,
        usageMonth: "2026-08",
        actualAudioMillis: 60_000,
        billedAudioMillis: 70_000,
        promptTokens: 120,
        completionTokens: 40,
        estimatedSpendMicrousd: 5_000,
      },
      glossary: [{ source: "Mistfall", target: "Mistfall" }],
    },
    runtime: {
      listening: true,
      microphoneActive: false,
      overlayEditMode: false,
      workerReady: true,
      workerModel: "silero-vad",
      groqSttBusy: false,
      groqStatus: "Groq พร้อมใช้งาน",
      budgetExhausted: false,
      attachedProcess: {
        pid: 4242,
        name: "MistfallHunter-Win64-Shipping.exe",
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        isMistfall: true,
      },
      effectiveCapturePid: 4000,
      effectiveCaptureName: "MistfallHunter.exe",
      effectiveOutputDeviceId: undefined,
      effectiveOutputDeviceName: undefined,
      effectiveOutputDeviceIsDefault: false,
      gameAudioRmsDbfs: -28,
      gameAudioPeakDbfs: -10,
      gameAudioLastSeenAtMs: now,
      gameVadActive: false,
      effectiveVadThreshold: 0.5,
      effectiveVadGainDb: 0,
      effectiveVadAutoGainDb: 0,
      droppedAudioChunks: 0,
      voiceChatAttachedProcess: {
        pid: 7210,
        name: "Discord.exe",
        executablePath: "C:\\Users\\User\\AppData\\Local\\Discord\\Discord.exe",
        displayName: "Discord",
        isMistfall: false,
      },
      voiceChatEffectiveCapturePid: 7000,
      voiceChatEffectiveCaptureName: "Discord.exe",
      voiceChatAudioRmsDbfs: -30,
      voiceChatAudioPeakDbfs: -12,
      voiceChatAudioLastSeenAtMs: now,
      voiceChatVadActive: false,
      voiceChatVadThreshold: 0.35,
      voiceChatVadGainDb: 6,
      voiceChatDroppedAudioChunks: 0,
      statusMessage: "กำลังฟัง Mistfall Hunter",
    },
    history: [
      {
        segmentId: "game-1",
        stream: "game",
        sourceDisplayName: "Mistfall Hunter",
        originalLanguage: "en",
        originalText: "Join us at the north gate.",
        translatedText: "ไปรวมกันที่ประตูเหนือ",
        status: "success",
        createdAtMs: now - 500,
      },
      {
        segmentId: "mic-1",
        stream: "microphone",
        originalLanguage: "th",
        originalText: "กำลังไป",
        translatedText: "On my way.",
        status: "success",
        createdAtMs: now - 1_000,
      },
    ],
  };
}
