export const gameScenes = [
  {
    id: "fps",
    label: "FPS",
    image: "wangai-first-person.webp",
    alt: "มุม First Person มือถืออาวุธและเพื่อนร่วมทีมในลานขนส่ง",
    english: "Stay together. I'll cover you.",
    thai: "อยู่ด้วยกันไว้ เดี๋ยวฉันคุ้มกันให้",
    replyThai: "โอเค ฉันจะตามไป",
    replyEnglish: "Okay, I'll follow you.",
  },
  {
    id: "fantasy",
    label: "แฟนตาซี",
    image: "wangai-fantasy.webp",
    alt: "มุม First Person ถือคทาเวทมนตร์ ตามเพื่อนร่วมทีมในดันเจียน",
    english: "Wait here. I'll check the next room.",
    thai: "รอตรงนี้นะ ฉันจะไปดูห้องถัดไป",
    replyThai: "ได้เลย ฉันจะรอตรงนี้",
    replyEnglish: "Sure, I'll wait here.",
  },
  {
    id: "survival",
    label: "เอาชีวิตรอด",
    image: "wangai-survival.webp",
    alt: "มุม First Person ถือขวานกับเพื่อนร่วมทีมสร้างที่พักในป่า",
    english: "We need more wood for the shelter.",
    thai: "เราต้องการไม้เพิ่มเพื่อสร้างที่พัก",
    replyThai: "ฉันจะไปเก็บไม้เพิ่ม",
    replyEnglish: "I'll gather more wood.",
  },
  {
    id: "farm",
    label: "ฟาร์ม",
    image: "wangai-farm.webp",
    alt: "มุม First Person รดน้ำผักกับเพื่อนในฟาร์ม",
    english: "Can you water the plants?",
    thai: "ช่วยรดน้ำต้นไม้หน่อยได้ไหม",
    replyThai: "ได้เลย เดี๋ยวฉันรดน้ำให้",
    replyEnglish: "Sure, I'll water them.",
  },
  {
    id: "racing",
    label: "แข่งรถ",
    image: "wangai-racing.webp",
    alt: "มุมมองหลังพวงมาลัยรถแข่ง เห็นรถคันหน้าในสนาม",
    english: "Slow down. There's a sharp turn ahead.",
    thai: "ช้าลงหน่อย ข้างหน้าเป็นโค้งหักศอก",
    replyThai: "รับทราบ ฉันจะลดความเร็ว",
    replyEnglish: "Got it. I'll slow down.",
  },
  {
    id: "space",
    label: "อวกาศ",
    image: "wangai-space.webp",
    alt: "มุมมองนักบินในยานอวกาศ เห็นยานเพื่อนและสถานีข้างหน้า",
    english: "Follow me to the docking station.",
    thai: "ตามฉันไปที่สถานีเทียบท่า",
    replyThai: "กำลังตามไป",
    replyEnglish: "I'm following you.",
  },
] as const;
